const schlossHeidegg = [
  {
    src: "schlossheidegg_001.jpg",
    location: "Schloss Heidegg",
    album: 1,
    style: 2,
  },
  {
    src: "schlossheidegg_002.jpg",
    location: "Schloss Heidegg",
    album: 1,
    style: 0,
  },
  {
    src: "schlossheidegg_003.jpg",
    location: "Schloss Heidegg",
    album: 1,
    style: 1,
  },
  {
    src: "schlossheidegg_004.jpg",
    location: "Schloss Heidegg",
    album: 1,
    style: 2,
  },
  {
    src: "schlossheidegg_005.jpg",
    location: "Schloss Heidegg",
    album: 1,
    style: 2,
  },
  {
    src: "schlossheidegg_006.jpg",
    location: "Schloss Heidegg",
    album: 1,
    style: 2,
  },
  {
    src: "schlossheidegg_007.jpg",
    location: "Schloss Heidegg",
    album: 1,
    style: 2,
  },
  {
    src: "schlossheidegg_008.jpg",
    location: "Schloss Heidegg",
    album: 1,
    style: 2,
  },
  {
    src: "schlossheidegg_009.jpg",
    location: "Schloss Heidegg",
    album: 1,
    style: 2,
  },
  {
    src: "schlossheidegg_010.jpg",
    location: "Schloss Heidegg",
    album: 1,
    style: 2,
  },
  {
    src: "schlossheidegg_011.jpg",
    location: "Schloss Heidegg",
    album: 1,
    style: 2,
  },
  {
    src: "schlossheidegg_012.jpg",
    location: "Schloss Heidegg",
    album: 1,
    style: 2,
  },
  {
    src: "schlossheidegg_013.jpg",
    location: "Schloss Heidegg",
    album: 1,
    style: 2,
  },
  {
    src: "schlossheidegg_014.jpg",
    location: "Schloss Heidegg",
    album: 1,
    style: 2,
  },
  {
    src: "schlossheidegg_015.jpg",
    location: "Schloss Heidegg",
    album: 1,
    style: 2,
  },
  {
    src: "schlossheidegg_016.jpg",
    location: "Schloss Heidegg",
    album: 1,
    style: 2,
  },
  {
    src: "schlossheidegg_017.jpg",
    location: "Schloss Heidegg",
    album: 1,
    style: 2,
  },
  {
    src: "schlossheidegg_018.jpg",
    location: "Schloss Heidegg",
    album: 1,
    style: 2,
  },
  {
    src: "schlossheidegg_019.jpg",
    location: "Schloss Heidegg",
    album: 1,
    style: 2,
  },

  {
    src: "schlossheidegg_020.jpg",
    location: "Schloss Heidegg",
    album: 1,
    style: 2,
  },
  {
    src: "schlossheidegg_021.jpg",
    location: "Schloss Heidegg",
    album: 1,
    style: 2,
  },
  {
    src: "schlossheidegg_022.jpg",
    location: "Schloss Heidegg",
    album: 1,
    style: 2,
  },
  {
    src: "schlossheidegg_023.jpg",
    location: "Schloss Heidegg",
    album: 1,
    style: 2,
  },
  {
    src: "schlossheidegg_024.jpg",
    location: "Schloss Heidegg",
    album: 1,
    style: 2,
  },
  {
    src: "schlossheidegg_025.jpg",
    location: "Schloss Heidegg",
    album: 1,
    style: 2,
  },
  {
    src: "schlossheidegg_026.jpg",
    location: "Schloss Heidegg",
    album: 1,
    style: 2,
  },
  {
    src: "photobox_001.jpg",
    location: "Photobox",
    album: 3,
    style: 2,
  },
  {
    src: "photobox_002.jpg",
    location: "Photobox",
    album: 3,
    style: 2,
  },
  {
    src: "photobox_003.jpg",
    location: "Photobox",
    album: 3,
    style: 2,
  },
  {
    src: "photobox_004.jpg",
    location: "Photobox",
    album: 3,
    style: 2,
  },
  {
    src: "photobox_005.jpg",
    location: "Photobox",
    album: 3,
    style: 2,
  },
  {
    src: "photobox_006.jpg",
    location: "Photobox",
    album: 3,
    style: 2,
  },
  {
    src: "photobox_007.jpg",
    location: "Photobox",
    album: 3,
    style: 2,
  },
  {
    src: "photobox_008.jpg",
    location: "Photobox",
    album: 3,
    style: 2,
  },
  {
    src: "photobox_009.jpg",
    location: "Photobox",
    album: 3,
    style: 2,
  },
  {
    src: "photobox_010.jpg",
    location: "Photobox",
    album: 3,
    style: 2,
  },
  {
    src: "photobox_011.jpg",
    location: "Photobox",
    album: 3,
    style: 2,
  },
  {
    src: "photobox_012.jpg",
    location: "Photobox",
    album: 3,
    style: 2,
  },
  {
    src: "photobox_013.jpg",
    location: "Photobox",
    album: 3,
    style: 2,
  },
  {
    src: "photobox_014.jpg",
    location: "Photobox",
    album: 3,
    style: 2,
  },
  {
    src: "photobox_015.jpg",
    location: "Photobox",
    album: 3,
    style: 2,
  },
  {
    src: "photobox_016.jpg",
    location: "Photobox",
    album: 3,
    style: 2,
  },
  {
    src: "photobox_017.jpg",
    location: "Photobox",
    album: 3,
    style: 2,
  },
  {
    src: "photobox_018.jpg",
    location: "Photobox",
    album: 3,
    style: 2,
  },
  {
    src: "photobox_019.jpg",
    location: "Photobox",
    album: 3,
    style: 2,
  },

  {
    src: "photobox_020.jpg",
    location: "Photobox",
    album: 3,
    style: 2,
  },
  {
    src: "photobox_021.jpg",
    location: "Photobox",
    album: 3,
    style: 2,
  },
  {
    src: "photobox_022.jpg",
    location: "Photobox",
    album: 3,
    style: 2,
  },
  {
    src: "photobox_023.jpg",
    location: "Photobox",
    album: 3,
    style: 2,
  },
  {
    src: "photobox_024.jpg",
    location: "Photobox",
    album: 3,
    style: 2,
  },
  {
    src: "photobox_025.jpg",
    location: "Photobox",
    album: 3,
    style: 2,
  },
  {
    src: "schifflaende_001.jpg",
    location: "Schifflände",
    album: 2,
    style: 2,
  },
  {
    src: "schifflaende_002.jpg",
    location: "Schifflände",
    album: 2,
    style: 2,
  },
  {
    src: "schifflaende_003.jpg",
    location: "Schifflände",
    album: 2,
    style: 2,
  },
  {
    src: "schifflaende_004.jpg",
    location: "Schifflände",
    album: 2,
    style: 2,
  },
  {
    src: "schifflaende_005.jpg",
    location: "Schifflände",
    album: 2,
    style: 2,
  },
  {
    src: "schifflaende_006.jpg",
    location: "Schifflände",
    album: 2,
    style: 2,
  },
  {
    src: "schifflaende_007.jpg",
    location: "Schifflände",
    album: 2,
    style: 2,
  },
  {
    src: "schifflaende_008.jpg",
    location: "Schifflände",
    album: 2,
    style: 2,
  },
  {
    src: "schifflaende_009.jpg",
    location: "Schifflände",
    album: 2,
    style: 2,
  },
  {
    src: "schifflaende_010.jpg",
    location: "Schifflände",
    album: 2,
    style: 2,
  },
  {
    src: "schifflaende_011.jpg",
    location: "Schifflände",
    album: 2,
    style: 2,
  },
  {
    src: "schifflaende_012.jpg",
    location: "Schifflände",
    album: 2,
    style: 2,
  },
  {
    src: "schifflaende_013.jpg",
    location: "Schifflände",
    album: 2,
    style: 2,
  },
  {
    src: "schifflaende_014.jpg",
    location: "Schifflände",
    album: 2,
    style: 2,
  },
  {
    src: "schifflaende_015.jpg",
    location: "Schifflände",
    album: 2,
    style: 2,
  },
  {
    src: "schifflaende_016.jpg",
    location: "Schifflände",
    album: 2,
    style: 2,
  },
  {
    src: "schifflaende_017.jpg",
    location: "Schifflände",
    album: 2,
    style: 2,
  },
  {
    src: "schifflaende_018.jpg",
    location: "Schifflände",
    album: 2,
    style: 2,
  },
  {
    src: "schifflaende_019.jpg",
    location: "Schifflände",
    album: 2,
    style: 2,
  },

  {
    src: "schifflaende_020.jpg",
    location: "Schifflände",
    album: 2,
    style: 2,
  },
  {
    src: "schifflaende_021.jpg",
    location: "Schifflände",
    album: 2,
    style: 2,
  },
  {
    src: "schifflaende_022.jpg",
    location: "Schifflände",
    album: 2,
    style: 2,
  },
  {
    src: "schifflaende_023.jpg",
    location: "Schifflände",
    album: 2,
    style: 2,
  },
  {
    src: "schifflaende_024.jpg",
    location: "Schifflände",
    album: 2,
    style: 2,
  },
  {
    src: "schifflaende_025.jpg",
    location: "Schifflände",
    album: 2,
    style: 2,
  },
];

export { schlossHeidegg };
